import htmlandcss from "./images/htmlandcss.png";
import javascript from "./images/javascript.png";
import react from "./images/react.png";
import node from "./images/node.png";
import next from "./images/next.png";
import tailwind from "./images/tailwind.png";
import react2 from "./images/react2.png";
import accessibility from "./images/accessibility.png";
import testing from "./images/testing.png";
import fullstack from "./images/fullstack.png";
import reactnative from "./images/reactnative.png";
import fluter from "./images/fluter.jpg";
import kotlin from "./images/kotlin.png";
import swift from "./images/swift.png";
import uiux from "./images/uiux.png";
import firebase from "./images/firebase.png";
import unity from "./images/unity.png";
import aso from "./images/aso.png";
import reactnativeadvanced from "./images/reactnativeadvanced.png";
import crossplatform from "./images/crossplatform.png";
import graphicdesign from "./images/graphicdesign.png";
import figma from "./images/figma.png";
import uxresearch from "./images/uxresearch.png";
import designsystem from "./images/designsystem.png";
import photoshop from "./images/photoshop.png";
import illustrator from "./images/illustrator.png";
import designthinking from "./images/designthinking.png";
import prototyping from "./images/prototyping.png";
import branding from "./images/branding.png";
import blender from "./images/blender.png";
import cprogramming from "./images/cprogramming.png";
import python from "./images/python.png";
import java from "./images/java.png";
import cpp from "./images/cpp.png";
import rust from "./images/rust.png";
import golang from "./images/golang.png";
import dsa from "./images/dsa.png";
import pseudocode from "./images/pseudocode.png";
import functionaljs from "./images/functionaljs.png";
import flask from "./images/flask.png";
import entrepreneurship from "./images/entrepreneurship.png";
import digitalmarketing from "./images/digitalmarketing.png";
import leadership from "./images/leadership.png";
import accounting from "./images/accounting.png";
import pmp from "./images/pmp.png";
import negotiation from "./images/negotiation.png";
import excel from "./images/excel.png";
import startupfunding from "./images/startupfunding.png";
import communication from "./images/communication.png";
import ecommerce from "./images/ecommerce.png";
import cyberfundamentals from "./images/cyberfundamentals.png";
import ethicalhacking from "./images/ethicalhacking.png";
import networksecurity from "./images/networksecurity.png";
import cloudsecurity from "./images/cloudsecurity.png";
import forensics from "./images/forensics.png";
import soc from "./images/soc.png";
import crypto from "./images/crypto.png";
import awareness from "./images/awareness.png";
import malware from "./images/malware.png";
import mlintro from "./images/mlintro.png";
const courseSeedData = [
  // === Web Development (1–10) ===
  {
    id: 1,
    category: "Web Development",
    title: "HTML & CSS Fundamentals",
    description:
      "Learn the basics of HTML and CSS to build beautiful static websites.",
    instructor: "Alice Johnson",
    duration: "4 weeks",
    rating: 4.6,
    students: 1200,
    level: "Beginner",
    featured: true,
    image: htmlandcss,
  },
  {
    id: 2,
    category: "Web Development",
    title: "JavaScript for Beginners",
    description: "Master JavaScript fundamentals and DOM manipulation.",
    instructor: "Ben Parker",
    duration: "5 weeks",
    rating: 4.7,
    students: 1500,
    level: "Beginner",
    featured: false,
    image: javascript,
  },
  {
    id: 3,
    category: "Web Development",
    title: "React Crash Course",
    description:
      "Create modern web interfaces using React, hooks, and components.",
    instructor: "Clara Smith",
    duration: "6 weeks",
    rating: 4.8,
    students: 980,
    level: "Intermediate",
    featured: true,
    image: react,
  },
  {
    id: 4,
    category: "Web Development",
    title: "Node.js Backend Development",
    description: "Learn to build fast APIs using Node.js and Express.",
    instructor: "David Kim",
    duration: "7 weeks",
    rating: 4.7,
    students: 830,
    level: "Intermediate",
    featured: false,
    image: node,
  },
  {
    id: 5,
    category: "Web Development",
    title: "Next.js Full Stack Guide",
    description:
      "Develop server-rendered applications using Next.js and MongoDB.",
    instructor: "Eleanor Green",
    duration: "8 weeks",
    rating: 4.9,
    students: 512,
    level: "Advanced",
    featured: true,
    image: next,
  },
  {
    id: 6,
    category: "Web Development",
    title: "Tailwind CSS Design System",
    description:
      "Create stunning designs with Tailwind and component patterns.",
    instructor: "Grace Lee",
    duration: "4 weeks",
    rating: 4.5,
    students: 612,
    level: "Beginner",
    featured: true,
    image: tailwind,
  },
  {
    id: 7,
    category: "Web Development",
    title: "Advanced React Patterns",
    description: "Learn context, reducers, and performance optimization.",
    instructor: "Harry Brown",
    duration: "6 weeks",
    rating: 4.8,
    students: 700,
    level: "Advanced",
    featured: false,
    image: react2,
  },
  {
    id: 8,
    category: "Web Development",
    title: "Web Accessibility Essentials",
    description:
      "Make websites accessible to everyone following WCAG guidelines.",
    instructor: "Isabella Lopez",
    duration: "3 weeks",
    rating: 4.5,
    students: 300,
    level: "All Levels",
    featured: false,
    image: accessibility,
  },
  {
    id: 9,
    category: "Web Development",
    title: "Testing React Apps",
    description:
      "Use Jest and React Testing Library to test components effectively.",
    instructor: "Jake Wilson",
    duration: "4 weeks",
    rating: 4.7,
    students: 295,
    level: "Intermediate",
    featured: false,
    image: testing,
  },
  {
    id: 10,
    category: "Web Development",
    title: "Full Stack Developer Roadmap",
    description: "A complete roadmap to becoming a full-stack web developer.",
    instructor: "Karen Thomas",
    duration: "12 weeks",
    rating: 4.9,
    students: 1900,
    level: "All Levels",
    featured: true,
    image: fullstack,
  },

  // === Mobile Development (11–20) ===
  {
    id: 11,
    category: "Mobile Development",
    title: "React Native Fundamentals",
    description: "Build native mobile apps using React Native and Expo.",
    instructor: "Liam White",
    duration: "6 weeks",
    rating: 4.8,
    students: 820,
    level: "Beginner",
    featured: true,
    image: reactnative,
  },
  {
    id: 12,
    category: "Mobile Development",
    title: "Flutter for Beginners",
    description:
      "Create cross-platform mobile apps with Google's Flutter framework.",
    instructor: "Maria Gomez",
    duration: "6 weeks",
    rating: 4.7,
    students: 760,
    level: "Beginner",
    featured: false,
    image: fluter,
  },
  {
    id: 13,
    category: "Mobile Development",
    title: "Android Development with Kotlin",
    description: "Develop native Android apps using Kotlin and Android Studio.",
    instructor: "Nathan King",
    duration: "8 weeks",
    rating: 4.6,
    students: 640,
    level: "Intermediate",
    featured: false,
    image: kotlin,
  },
  {
    id: 14,
    category: "Mobile Development",
    title: "iOS Development with Swift",
    description: "Learn Swift and build beautiful iOS applications.",
    instructor: "Olivia Evans",
    duration: "8 weeks",
    rating: 4.7,
    students: 590,
    level: "Intermediate",
    featured: true,
    image: swift,
  },
  {
    id: 15,
    category: "Mobile Development",
    title: "Mobile UI/UX Design",
    description: "Design user-friendly mobile interfaces with Figma.",
    instructor: "Paul Adams",
    duration: "4 weeks",
    rating: 4.5,
    students: 490,
    level: "Beginner",
    featured: false,
    image: uiux,
  },
  {
    id: 16,
    category: "Mobile Development",
    title: "Firebase Integration for Apps",
    description: "Add authentication and cloud storage using Firebase.",
    instructor: "Quinn Anderson",
    duration: "3 weeks",
    rating: 4.6,
    students: 520,
    level: "Intermediate",
    featured: false,
    image: firebase,
  },
  {
    id: 17,
    category: "Mobile Development",
    title: "Mobile Game Development with Unity",
    description: "Create 2D and 3D games for Android and iOS with Unity.",
    instructor: "Ryan Moore",
    duration: "9 weeks",
    rating: 4.8,
    students: 870,
    level: "Advanced",
    featured: true,
    image: unity,
  },
  {
    id: 18,
    category: "Mobile Development",
    title: "App Store Optimization (ASO)",
    description: "Learn strategies to improve app rankings in app stores.",
    instructor: "Sophia Green",
    duration: "2 weeks",
    rating: 4.3,
    students: 310,
    level: "All Levels",
    featured: false,
    image: aso,
  },
  {
    id: 19,
    category: "Mobile Development",
    title: "React Native Advanced Projects",
    description:
      "Develop advanced features like push notifications and deep linking.",
    instructor: "Thomas King",
    duration: "6 weeks",
    rating: 4.8,
    students: 440,
    level: "Advanced",
    featured: false,
    image: reactnativeadvanced,
  },
  {
    id: 20,
    category: "Mobile Development",
    title: "Cross-Platform Development Tools",
    description: "Explore frameworks like Ionic, Xamarin, and Flutter.",
    instructor: "Uma Patel",
    duration: "5 weeks",
    rating: 4.6,
    students: 520,
    level: "All Levels",
    featured: true,
    image: crossplatform,
  },

  // === Design (21–30) ===
  {
    id: 21,
    category: "Design",
    title: "Graphic Design Basics",
    description: "Learn color theory, typography, and layout fundamentals.",
    instructor: "Victor Ross",
    duration: "4 weeks",
    rating: 4.6,
    students: 720,
    level: "Beginner",
    featured: true,
    image: graphicdesign,
  },
  {
    id: 22,
    category: "Design",
    title: "UI Design with Figma",
    description: "Master Figma tools to create beautiful interfaces.",
    instructor: "Wendy Clark",
    duration: "5 weeks",
    rating: 4.7,
    students: 890,
    level: "Intermediate",
    featured: true,
    image: figma,
  },
  {
    id: 23,
    category: "Design",
    title: "UX Research Fundamentals",
    description: "Conduct user interviews and usability tests effectively.",
    instructor: "Xavier Hall",
    duration: "3 weeks",
    rating: 4.5,
    students: 430,
    level: "Intermediate",
    featured: false,
    image: uxresearch,
  },
  {
    id: 24,
    category: "Design",
    title: "Prototyping & Wireframing",
    description:
      "Turn ideas into interactive prototypes using Figma and Adobe XD.",
    instructor: "Yara Brooks",
    duration: "4 weeks",
    rating: 4.6,
    students: 570,
    level: "Beginner",
    featured: false,
    image: prototyping,
  },
  {
    id: 25,
    category: "Design",
    title: "Design Systems & Style Guides",
    description: "Build scalable design systems for consistent UI.",
    instructor: "Zach Collins",
    duration: "6 weeks",
    rating: 4.8,
    students: 380,
    level: "Advanced",
    featured: true,
    image: designsystem,
  },
  {
    id: 26,
    category: "Design",
    title: "Photoshop Masterclass",
    description: "Learn professional photo editing and digital art creation.",
    instructor: "Amy Brown",
    duration: "5 weeks",
    rating: 4.7,
    students: 1000,
    level: "Intermediate",
    featured: true,
    image: photoshop,
  },
  {
    id: 27,
    category: "Design",
    title: "Illustrator for Beginners",
    description:
      "Create vector graphics and illustrations using Adobe Illustrator.",
    instructor: "Brian Foster",
    duration: "4 weeks",
    rating: 4.6,
    students: 860,
    level: "Beginner",
    featured: false,
    image: illustrator,
  },
  {
    id: 28,
    category: "Design",
    title: "Design Thinking Workshop",
    description:
      "Understand creative problem-solving with design thinking methods.",
    instructor: "Clara James",
    duration: "3 weeks",
    rating: 4.5,
    students: 640,
    level: "All Levels",
    featured: false,
    image: designthinking,
  },
  {
    id: 29,
    category: "Design",
    title: "Branding & Visual Identity",
    description: "Develop a strong brand presence and consistent visual style.",
    instructor: "Daniel Young",
    duration: "6 weeks",
    rating: 4.8,
    students: 580,
    level: "Advanced",
    featured: true,
    image: branding,
  },
  {
    id: 30,
    category: "Design",
    title: "3D Design with Blender",
    description: "Model and render 3D scenes using Blender software.",
    instructor: "Emily Carter",
    duration: "8 weeks",
    rating: 4.9,
    students: 950,
    level: "Advanced",
    featured: true,
    image: blender,
  },

  // === Programming (31–40) ===
  {
    id: 31,
    category: "Programming",
    title: "C Programming Fundamentals",
    description: "Learn the basics of C programming and memory management.",
    instructor: "Frank Adams",
    duration: "5 weeks",
    rating: 4.5,
    students: 820,
    level: "Beginner",
    featured: true,
    image: cprogramming,
  },
  {
    id: 32,
    category: "Programming",
    title: "Python Programming Masterclass",
    description: "Start coding in Python with real-world exercises.",
    instructor: "Grace Li",
    duration: "6 weeks",
    rating: 4.8,
    students: 2100,
    level: "All Levels",
    featured: true,
    image: python,
  },
  {
    id: 33,
    category: "Programming",
    title: "Java for Beginners",
    description: "Object-oriented programming using Java language.",
    instructor: "Hannah Brown",
    duration: "7 weeks",
    rating: 4.7,
    students: 1250,
    level: "Beginner",
    featured: false,
    image: java,
  },
  {
    id: 34,
    category: "Programming",
    title: "C++ Programming Advanced",
    description:
      "Learn advanced concepts like templates, pointers, and OOP in C++.",
    instructor: "Ian Miller",
    duration: "8 weeks",
    rating: 4.6,
    students: 890,
    level: "Advanced",
    featured: false,
    image: cpp,
  },
  {
    id: 35,
    category: "Programming",
    title: "Rust for Systems Programming",
    description: "Explore memory safety and concurrency with Rust.",
    instructor: "Jane Wilson",
    duration: "6 weeks",
    rating: 4.8,
    students: 610,
    level: "Intermediate",
    featured: true,
    image: rust,
  },
  {
    id: 36,
    category: "Programming",
    title: "Go Programming Essentials",
    description: "Develop concurrent apps using Golang and goroutines.",
    instructor: "Kevin Brown",
    duration: "5 weeks",
    rating: 4.7,
    students: 480,
    level: "Intermediate",
    featured: false,
    image: golang,
  },
  {
    id: 37,
    category: "Programming",
    title: "Data Structures & Algorithms",
    description: "Master algorithms, sorting, and searching for interviews.",
    instructor: "Laura Scott",
    duration: "9 weeks",
    rating: 4.9,
    students: 1750,
    level: "Advanced",
    featured: true,
    image: dsa,
  },
  {
    id: 38,
    category: "Programming",
    title: "Programming Logic with Pseudocode",
    description:
      "Learn how to design algorithms using flowcharts and pseudocode.",
    instructor: "Mark Turner",
    duration: "4 weeks",
    rating: 4.4,
    students: 400,
    level: "Beginner",
    featured: false,
    image: pseudocode,
  },
  {
    id: 39,
    category: "Programming",
    title: "Functional Programming in JavaScript",
    description: "Use functional concepts like map, filter, and reduce.",
    instructor: "Nina Torres",
    duration: "5 weeks",
    rating: 4.6,
    students: 530,
    level: "Intermediate",
    featured: false,
    image: functionaljs,
  },
  {
    id: 40,
    category: "Programming",
    title: "API Development with Python Flask",
    description: "Build and deploy APIs using Flask and REST principles.",
    instructor: "Oliver Hughes",
    duration: "6 weeks",
    rating: 4.8,
    students: 950,
    level: "Intermediate",
    featured: true,
    image: flask,
  },

  // === Business (41–50) ===
  {
    id: 41,
    category: "Business",
    title: "Entrepreneurship 101",
    description: "Learn how to launch, manage, and scale your business idea.",
    instructor: "Paula Carter",
    duration: "6 weeks",
    rating: 4.7,
    students: 1300,
    level: "All Levels",
    featured: true,
    image: entrepreneurship,
  },
  {
    id: 42,
    category: "Business",
    title: "Digital Marketing Strategy",
    description: "Develop marketing campaigns and SEO strategies.",
    instructor: "Quinn Brooks",
    duration: "5 weeks",
    rating: 4.6,
    students: 850,
    level: "Intermediate",
    featured: false,
    image: digitalmarketing,
  },
  {
    id: 43,
    category: "Business",
    title: "Leadership & Management Skills",
    description: "Improve your leadership and decision-making abilities.",
    instructor: "Rachel Kim",
    duration: "4 weeks",
    rating: 4.8,
    students: 920,
    level: "All Levels",
    featured: true,
    image: leadership,
  },
  {
    id: 44,
    category: "Business",
    title: "Financial Accounting Basics",
    description: "Understand financial statements and accounting principles.",
    instructor: "Samuel Lewis",
    duration: "6 weeks",
    rating: 4.7,
    students: 680,
    level: "Beginner",
    featured: false,
    image: accounting,
  },
  {
    id: 45,
    category: "Business",
    title: "Project Management Professional (PMP)",
    description:
      "Prepare for the PMP certification with project management essentials.",
    instructor: "Tina Gray",
    duration: "8 weeks",
    rating: 4.8,
    students: 740,
    level: "Advanced",
    featured: true,
    image: pmp,
  },
  {
    id: 46,
    category: "Business",
    title: "Negotiation Skills Workshop",
    description: "Develop effective communication and persuasion techniques.",
    instructor: "Umar Ahmed",
    duration: "3 weeks",
    rating: 4.5,
    students: 480,
    level: "All Levels",
    featured: false,
    image: negotiation,
  },
  {
    id: 47,
    category: "Business",
    title: "Business Analytics with Excel",
    description: "Analyze data and make business decisions using Excel tools.",
    instructor: "Victor Green",
    duration: "5 weeks",
    rating: 4.6,
    students: 560,
    level: "Intermediate",
    featured: false,
    image: excel,
  },
  {
    id: 48,
    category: "Business",
    title: "Startup Funding and Investment",
    description:
      "Understand venture capital, angel investing, and pitch decks.",
    instructor: "Wendy Adams",
    duration: "6 weeks",
    rating: 4.7,
    students: 370,
    level: "Advanced",
    featured: true,
    image: startupfunding,
  },
  {
    id: 49,
    category: "Business",
    title: "Business Communication Mastery",
    description: "Enhance your verbal and written business communication.",
    instructor: "Xander Thomas",
    duration: "4 weeks",
    rating: 4.5,
    students: 410,
    level: "All Levels",
    featured: false,
    image: communication,
  },
  {
    id: 50,
    category: "Business",
    title: "E-commerce Business Bootcamp",
    description:
      "Learn to build and scale online stores using Shopify and WooCommerce.",
    instructor: "Yasmin Parker",
    duration: "7 weeks",
    rating: 4.8,
    students: 1050,
    level: "Intermediate",
    featured: true,
    image: ecommerce,
  },

  // === Cybersecurity (51–60) ===
  {
    id: 51,
    category: "Cybersecurity",
    title: "Cybersecurity Fundamentals",
    description:
      "Learn the basics of information security and threat analysis.",
    instructor: "Zane Brooks",
    duration: "6 weeks",
    rating: 4.7,
    students: 620,
    level: "Beginner",
    featured: true,
    image: cyberfundamentals,
  },
  {
    id: 52,
    category: "Cybersecurity",
    title: "Ethical Hacking for Beginners",
    description: "Learn penetration testing and vulnerability scanning.",
    instructor: "Amy Williams",
    duration: "8 weeks",
    rating: 4.8,
    students: 780,
    level: "Intermediate",
    featured: true,
    image: ethicalhacking,
  },
  {
    id: 53,
    category: "Cybersecurity",
    title: "Network Security Essentials",
    description:
      "Understand firewalls, VPNs, and secure network architectures.",
    instructor: "Brian Davis",
    duration: "5 weeks",
    rating: 4.6,
    students: 490,
    level: "Intermediate",
    featured: false,
    image: networksecurity,
  },
  {
    id: 54,
    category: "Cybersecurity",
    title: "Cloud Security",
    description: "Secure cloud infrastructures in AWS and Azure.",
    instructor: "Clara Roberts",
    duration: "7 weeks",
    rating: 4.7,
    students: 510,
    level: "Advanced",
    featured: false,
    image: cloudsecurity,
  },
  {
    id: 55,
    category: "Cybersecurity",
    title: "Incident Response & Forensics",
    description: "Learn how to investigate and respond to cyber incidents.",
    instructor: "Daniel Martin",
    duration: "6 weeks",
    rating: 4.7,
    students: 380,
    level: "Advanced",
    featured: true,
    image: forensics,
  },
  {
    id: 56,
    category: "Cybersecurity",
    title: "Security Operations Center (SOC)",
    description:
      "Monitor, detect, and respond to cyber threats in a SOC environment.",
    instructor: "Ella Johnson",
    duration: "8 weeks",
    rating: 4.8,
    students: 460,
    level: "Advanced",
    featured: false,
    image: soc,
  },
  {
    id: 57,
    category: "Cybersecurity",
    title: "Cryptography Basics",
    description: "Understand encryption, hashing, and digital signatures.",
    instructor: "Fred Harris",
    duration: "5 weeks",
    rating: 4.5,
    students: 430,
    level: "Intermediate",
    featured: false,
    image: crypto,
  },
  {
    id: 58,
    category: "Cybersecurity",
    title: "Security Awareness Training",
    description:
      "Teach employees how to identify phishing and social engineering.",
    instructor: "Gina Taylor",
    duration: "3 weeks",
    rating: 4.4,
    students: 270,
    level: "All Levels",
    featured: false,
    image: awareness,
  },
  {
    id: 59,
    category: "Cybersecurity",
    title: "Malware Analysis",
    description:
      "Dissect and analyze malicious software using sandboxing tools.",
    instructor: "Henry White",
    duration: "7 weeks",
    rating: 4.8,
    students: 510,
    level: "Advanced",
    featured: true,
    image: malware,
  },
  {
    id: 60,
    category: "Machine Learning",
    title: "Introduction to Machine Learning",
    description: "Understand supervised and unsupervised learning basics.",
    instructor: "Ivy Nguyen",
    duration: "8 weeks",
    rating: 4.9,
    students: 1800,
    level: "All Levels",
    featured: true,
    image: mlintro,
  },
  // you can continue ML 61–70 if you want more later
];
export default courseSeedData;
