// translations.js
export const translations = {
  english: {
    settings: "Settings",
    accountSettings: "Account Settings",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    pushNotifications: "Push Notifications",
    theme: "Theme",
    language: "Language",
    languageDescription: "Select your preferred language",
    fontSize: "Font Size",
    twoFactorAuth: "Two-Factor Authentication",
    dataExport: "Data Export",
    autoLogout: "Auto Logout",
    showOnlineStatus: "Show Online Status",
    courseUpdates: "Course Updates",
    liveClassReminders: "Live Class Reminders",
    assignmentDeadlines: "Assignment Deadlines",
    promotionalEmails: "Promotional Emails",
    saveSettings: "Save Settings",
    cancel: "Cancel"
  },
 khmer: {
  settings: "ការកំណត់",
  accountSettings: "ការកំណត់គណនី",
  emailNotifications: "ការជូនដំណឹងអ៊ីមែល",
  smsNotifications: "ការជូនដំណឹង SMS",
  pushNotifications: "ការជូនដំណឹងទូរស័ព្ទ",
  theme: "បែបផែន",
  language: "ភាសា",
  languageDescription: "ជ្រើសភាសាដែលអ្នកចូលចិត្ត",
  fontSize: "ទំហំអក្សរ",
  twoFactorAuth: "ការផ្ទៀងផ្ទាត់ពីរ ដំណាក់កាល",
  dataExport: "នាំចេញទិន្នន័យ",
  autoLogout: "ចាកចេញដោយស្វ័យប្រវត្តិ",
  showOnlineStatus: "បង្ហាញស្ថានភាពអនឡាញ",
  courseUpdates: "ព័ត៌មានអំពីវគ្គសិក្សា",
  liveClassReminders: "ការរំលឹកថ្នាក់បន្តផ្ទាល់",
  assignmentDeadlines: "កាលបរិច្ឆេទកំណត់មុខងារ",
  promotionalEmails: "អ៊ីមែលផ្សព្វផ្សាយ",
  saveSettings: "រក្សាទុកការកំណត់",
  cancel: "បោះបង់"
},
chinese: {
  settings: "设置",
  accountSettings: "账户设置",
  emailNotifications: "电子邮件通知",
  smsNotifications: "短信通知",
  pushNotifications: "推送通知",
  theme: "主题",
  language: "语言",
  languageDescription: "选择您喜欢的语言",
  fontSize: "字体大小",
  twoFactorAuth: "双重验证",
  dataExport: "数据导出",
  autoLogout: "自动登出",
  showOnlineStatus: "显示在线状态",
  courseUpdates: "课程更新",
  liveClassReminders: "直播课程提醒",
  assignmentDeadlines: "作业截止日期",
  promotionalEmails: "推广邮件",
  saveSettings: "保存设置",
  cancel: "取消"
},
spanish: {
    settings: "Configuración",
    accountSettings: "Configuración de la cuenta",
    emailNotifications: "Notificaciones por correo electrónico",
    smsNotifications: "Notificaciones por SMS",
    pushNotifications: "Notificaciones push",
    theme: "Tema",
    language: "Idioma",
    languageDescription: "Elija su idioma preferido",
    fontSize: "Tamaño de fuente",
    twoFactorAuth: "Autenticación de dos factores",
    dataExport: "Exportación de datos",
    autoLogout: "Cierre de sesión automático",
    showOnlineStatus: "Mostrar estado en línea",
    courseUpdates: "Actualizaciones del curso",
    liveClassReminders: "Recordatorios de clases en vivo",
    assignmentDeadlines: "Fechas límite de tareas",
    promotionalEmails: "Correos electrónicos promocionales",
    saveSettings: "Guardar configuración",
    cancel: "Cancelar",
},

};
